### ISSUE TITLE
Composed command line is wierd

### ISSUE THREAD

**Issue by fuchen** [alefragnani/useful-context-menu#4]
The composed command line is something like: `start "" "C:\Windows\System32\cmd.exe`, which is incorrect.

`openTerminal` function should be modified:

```
  openTerminal: (dirpath) ->
    app = "C:\\Windows\\System32\\cmd.exe"
    args = ''
    cmdline = "\"#{app}\ #{args}\""
    cmdline = "start " + cmdline
    exec cmdline, cwd: dirpath
```

**Comment by alefragnani** [comment]
Hi, sorry for the delay,

The only difference that I noted is that now the Command Prompt window will have a _title_ (C:\Windows\System32\cmd.exe in my case). 

Is that it? Do you have other problem?
