### ISSUE TITLE
Suggestion - Configure Menu

### ISSUE THREAD

**Issue by tatoosh** [alefragnani/useful-context-menu#6]
It would be nice to configure right click menu.
So i can open an console app with arg.

**Comment by alefragnani** [comment]
Hi @tatoosh ,

Do you mean the `Open in Terminal` command?

**Comment by tatoosh** [comment]
@alefragnani: yes or a custom command for a Windows batch file.

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
